app:
  build: .
  environment:
    EMAIL_HOST: "localhost:3000"
    RAILS_ENV: development
  ports:
    - "3000:3000"
  volumes:
    - ".:/workspace"
  links:
    - mysql
    - mailcatcher

mysql:
  image: mysql:5.7.22
  ports:
    - "3306:3306"
  volumes:
    - "./tmp/mysql:/var/lib/mysql"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=dev

mailcatcher:
  image: tophfr/mailcatcher
  ports:
    - "1080:80"
    - "1025:25"
