mysql:
  image: mysql:5.7.22
  ports:
    - "3306:3306"
  volumes:
    - "./tmp/mysql:/var/lib/mysql"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=dev

app:
  build: .
  environment:
    RAILS_ENV: development
  ports:
    - "3000:3000"
  volumes:
    - ".:/workspace"
  links:
    - "mysql"
