app:
  build: .
  environment:
    EMAIL_HOST: "localhost:3000"
    EMAIL_SENDER: development@bolaocopa.com
    RAILS_ENV: development
  ports:
    - "3000:3000"
  volumes:
    - ".:/workspace"
  links:
    - postgres
    - mailcatcher

postgres:
  image: postgres:9.6
  ports:
    - "5432:5432"
  volumes:
    - "./docker/volumes/postgres:/var/lib/postgresql/data"
  environment:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root

mailcatcher:
  image: tophfr/mailcatcher
  ports:
    - "1080:80"
    - "1025:25"
