# config/app.yml for rails-settings-cached
defaults: &defaults
  predictions:
    hours_before_game_to_open: 168
    hours_before_game_to_close: 5
  score:
    home_score: 1
    away_score: 1
    game_winner: 1
    score_difference: 1
    penalty_result: 1
    penalty_winner: 1
    match_winner: 1

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
