default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: postgres

development:
  <<: *default
  database: world_cup_predictions_development

test:
  <<: *default
  database: world_cup_predictions_test
